### ISSUE TITLE
AttributeError: 'float' object has no attribute 'split'

### ISSUE THREAD

**Issue by xlxxlup** [zdaiot/Kaggle-Steel-Defect-Detection#5]
yolov5) D:\steel-de\Kaggle-Steel-Defect-Detection-master\Kaggle-Steel-Defect-Detection-master>python train_classify.py --model_name=unet_resnet34 --batch_size=48 --lr=0.0005 --epoch=1
Using model: unet_resnet34
  0%|                                                                                                                                                                                          | 0/210 [00:55<?, ?it/s]

Traceback (most recent call last):
  File "train_classify.py", line 176, in <module>
    train_val.train(train_loader, valid_loader)
  File "train_classify.py", line 78, in train
    for i, (images, labels) in enumerate(tbar):
  File "D:\Anaconda\Anaconda\envs\yolov5\lib\site-packages\tqdm\std.py", line 1181, in __iter__
    for obj in iterable:
  File "D:\Anaconda\Anaconda\envs\yolov5\lib\site-packages\torch\utils\data\dataloader.py", line 630, in __next__
    data = self._next_data()
  File "D:\Anaconda\Anaconda\envs\yolov5\lib\site-packages\torch\utils\data\dataloader.py", line 1345, in _next_data
    return self._process_data(data)
  File "D:\Anaconda\Anaconda\envs\yolov5\lib\site-packages\torch\utils\data\dataloader.py", line 1371, in _process_data
    data.reraise()
  File "D:\Anaconda\Anaconda\envs\yolov5\lib\site-packages\torch\_utils.py", line 694, in reraise
    raise exception
AttributeError: Caught AttributeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "D:\Anaconda\Anaconda\envs\yolov5\lib\site-packages\torch\utils\data\_utils\worker.py", line 308, in _worker_loop
    data = fetcher.fetch(index)
  File "D:\Anaconda\Anaconda\envs\yolov5\lib\site-packages\torch\utils\data\_utils\fetch.py", line 51, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "D:\Anaconda\Anaconda\envs\yolov5\lib\site-packages\torch\utils\data\_utils\fetch.py", line 51, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "D:\steel-de\Kaggle-Steel-Defect-Detection-master\Kaggle-Steel-Defect-Detection-master\datasets\steel_dataset.py", line 68, in __getitem__
    image_id, mask = make_mask(idx, self.df)
  File "D:\steel-de\Kaggle-Steel-Defect-Detection-master\Kaggle-Steel-Defect-Detection-master\utils\rle_parse.py", line 26, in make_mask
    label = label.split(" ")
AttributeError: 'float' object has no attribute 'split'  请问下这是什么原因

**Comment by xlxxlup** [comment]
模型下载完之后  就不动了

**Comment by zhoujuan0305** [comment]
把 if label is not np.nan
改成if not pd.isna(label)
